// AUTO-GENERATED by generate-kie-apiframe-catalogs.mjs. Do not hand-edit:
// this file is overwritten on every regeneration to stay in sync with the
// describe JSON files in this directory and the provider whitelist.
import imageFlux2Pro from './image__flux-2-pro.json';
import imageGptImage15 from './image__gpt-image-1.5.json';
import imageNanoBananaPro from './image__nano-banana-pro.json';
import imageSeedream5Pro from './image__seedream-5-pro.json';
import musicMureka from './music__mureka.json';
import musicSuno from './music__suno.json';
import videoKling30 from './video__kling-3.0.json';
import videoSeedance2 from './video__seedance-2.json';
import videoSora2Pro from './video__sora-2-pro.json';
import videoVeo31 from './video__veo-3.1.json';

export type ApiframeDescribeEntry = {
  locator: string;
  modelId: string;
  providerId: 'apiframe';
  modality: string;
  label: string;
  outputType: string;
  endpoint: {
    method: string;
    path: string;
  };
  requestSchema: Record<string, unknown>;
  wireMetadata: {
    modelField: string;
    paramsField: string | null;
    wirePath: string | null;
  };
};

const DESCRIBE_ENTRIES: ApiframeDescribeEntry[] = [
  imageFlux2Pro,
  imageGptImage15,
  imageNanoBananaPro,
  imageSeedream5Pro,
  musicMureka,
  musicSuno,
  videoKling30,
  videoSeedance2,
  videoSora2Pro,
  videoVeo31,
] as ApiframeDescribeEntry[];

const describeByLocator = new Map(
  DESCRIBE_ENTRIES.map(entry => [entry.locator, entry]),
);

export function getApiframeDescribeEntry(locator: string): ApiframeDescribeEntry | undefined {
  return describeByLocator.get(locator);
}

export function listApiframeDescribeLocators(): string[] {
  return [...describeByLocator.keys()].sort((left, right) => left.localeCompare(right));
}
