// AUTO-GENERATED by generate-kie-apiframe-catalogs.mjs. Do not hand-edit:
// this file is overwritten on every regeneration to stay in sync with the
// describe JSON files in this directory and the provider whitelist.
import marketBytedanceSeedance2 from './market__bytedance__seedance-2.json';
import marketBytedanceSeedance2Fast from './market__bytedance__seedance-2-fast.json';
import marketElevenlabsTextToDialogueV3 from './market__elevenlabs__text-to-dialogue-v3.json';
import marketElevenlabsTextToSpeechMultilingualV2 from './market__elevenlabs__text-to-speech-multilingual-v2.json';
import marketFlux2ProImageToImage from './market__flux-2__pro-image-to-image.json';
import marketFlux2ProTextToImage from './market__flux-2__pro-text-to-image.json';
import marketGrokImagineImageToImage from './market__grok-imagine__image-to-image.json';
import marketGrokImagineTextToImage from './market__grok-imagine__text-to-image.json';
import marketKling30MotionControl from './market__kling-3.0__motion-control.json';
import marketKling30Video from './market__kling-3.0__video.json';
import marketSeedream5ProImageToImage from './market__seedream__5-pro-image-to-image.json';
import marketSeedream5ProTextToImage from './market__seedream__5-pro-text-to-image.json';

export type KieDescribeEntry = {
  locator: string;
  modelId: string;
  providerId: 'kie';
  outputType: string;
  label: string;
  endpoint: {
    method: string;
    path: string;
  };
  requestSchema: Record<string, unknown>;
  wireMetadata: {
    modelField: string;
    inputField: string;
    callbackField: string;
  };
};

const DESCRIBE_ENTRIES: KieDescribeEntry[] = [
  marketBytedanceSeedance2,
  marketBytedanceSeedance2Fast,
  marketElevenlabsTextToDialogueV3,
  marketElevenlabsTextToSpeechMultilingualV2,
  marketFlux2ProImageToImage,
  marketFlux2ProTextToImage,
  marketGrokImagineImageToImage,
  marketGrokImagineTextToImage,
  marketKling30MotionControl,
  marketKling30Video,
  marketSeedream5ProImageToImage,
  marketSeedream5ProTextToImage,
] as KieDescribeEntry[];

const describeByLocator = new Map(
  DESCRIBE_ENTRIES.map(entry => [entry.locator, entry]),
);

export function getKieDescribeEntry(locator: string): KieDescribeEntry | undefined {
  return describeByLocator.get(locator);
}

export function listKieDescribeLocators(): string[] {
  return [...describeByLocator.keys()].sort((left, right) => left.localeCompare(right));
}
